---
- ansible.builtin.import_tasks: apt.yml
- ansible.builtin.import_tasks: rabbitmq.yml

- name: Install amplet2-client
  ansible.builtin.apt:
    pkg:
      - amplet2-client
    state: present

- name: Remove default amplet2-client configuration files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/amplet2/clients/default.conf
    - /etc/amplet2/clients/client.example

- name: Configure individual amplet2 clients
  ansible.builtin.include_tasks:
    file: amplet2.yml
  loop: "{{ amp }}"
  loop_control:
    loop_var: amp_item
    label: "{{ amp_item.name }}"

# setgid on top level directory so new directories created by amplet2-client
# have the correct group and can be read by things that need them
- name: Ensure setgid bit set on keys directory
  ansible.builtin.file:
    path: /etc/amplet2/keys/
    state: directory
    owner: amplet
    group: amplet
    mode: "2750"

- name: Check amplet2-client is running
  ansible.builtin.service:
    name: amplet2-client.service
    state: started
