---

- import_tasks: apt.yml
- import_tasks: rabbitmq.yml

- name: Install amplet2-client
  apt:
    pkg:
      - amplet2-client
    state: present

- name: Remove default amplet2-client configuration files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/amplet2/clients/default.conf
    - /etc/amplet2/clients/client.example

- name: Configure individual amplet2 clients
  include_tasks: amplet2.yml
  with_items: "{{ amp }}"
  loop_control:
    loop_var: amp_item

# setgid on top level directory so new directories created by amplet2-client
# have the correct group and can be read by things that need them
- name: Ensure setgid bit set on keys directory
  file:
    path: /etc/amplet2/keys/
    state: directory
    owner: amplet
    group: amplet
    mode: "2750"

- name: Check amplet2-client is running
  service:
    name: amplet2-client.service
    state: started
