---
- name: Converge
  hosts: all
  tasks:
    - name: "Include wandansible.amp.client"
      ansible.builtin.include_role:
        name: "wandansible.amp.client"
      vars:
        amp:
          - name: "{{ inventory_hostname }}"
            collector: "localhost"
            collector_cacert: |
              -----BEGIN CERTIFICATE-----
              MIIBfjCCASWgAwIBAgIUChUyl5juL4tN3AEew63tEFeGvBYwCgYIKoZIzj0EAwIw
              FTETMBEGA1UEAwwKQW5zaWJsZSBDQTAeFw0yMjA5MjgwNDI5MzNaFw0zNzA5MjQw
              NDI5MzNaMBUxEzARBgNVBAMMCkFuc2libGUgQ0EwWTATBgcqhkjOPQIBBggqhkjO
              PQMBBwNCAAQrXff///ps/j0FBYZ10rjcG5xQWcNwrzhKOS54vmcVG0DurN9i63ib
              agMKRCiIqgYazR8VShimwILQdeujL4HQo1MwUTAdBgNVHQ4EFgQUyHgLi+GfXd78
              tEe1V48X9UWlNdwwHwYDVR0jBBgwFoAUyHgLi+GfXd78tEe1V48X9UWlNdwwDwYD
              VR0TAQH/BAUwAwEB/zAKBggqhkjOPQQDAgNHADBEAiAJr2eRfFIZPg8afB6nbxzt
              bexFX5LFVXp3w9iSZFApZAIgMjvvHU6xuMitPJLkEqUo2J1JNEmO/EVNl46j2BJ/
              jU0=
              -----END CERTIFICATE-----
